services:


  web:


    image: php:8.2-apache


    container_name: ikerweb


    ports:


      - "8080:80"


    volumes:


      - ./src:/var/www/html


    environment:


      DB_HOST: db


      DB_NAME: tareas_db


      DB_USER: root


      DB_PASS: root1234


    depends_on:


      - db


    command: >


      bash -c "docker-php-ext-install pdo pdo_mysql mysqli &&


               apache2-foreground"


  db:


    image: mysql:8.0


    container_name: ikerdb


    environment:


      MYSQL_ROOT_PASSWORD: root1234


      MYSQL_DATABASE: tareas_db


    volumes:


      - mysql_data:/var/lib/mysql


      - ./sql:/docker-entrypoint-initdb.d


    ports:


      - "3307:3306"


volumes:


  mysql_data:
